name: Render Quarto Document

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "scales"))'
      - name: Render Quarto document
        run: |
          quarto render diamonds-plot.qmd
